language: ruby
rvm:
- 2.7.1

# Configure the RAINFOREST_TOKEN environment variable. You can get the secure
# string by running 'travis encrypt RAINFOREST_TOKEN=<my_token>'
env:
  global:
    secure: A/8sE0BBzCjRiG4EwmthvbueOUqZikyrWWyD4ICNa8TyFptuls8peFxrLuUV6xgjVOqHzqQVKwzKXudAsxTE4rEBz2j7KNSA+LYWacorhaD1eDW2+HxyBHzonSVpsHxl/ZF2ZdrJyIOREgAzT2L1qGr9Wk45+qDYVgC4Y3XNRos=

install:
  - bundle install

  # Install the latests version of rainforest-cli. This will allow us to
  # trigger a Rainforest run after each deploy.
  - gem install rainforest-cli

deploy:
  # Deploy to our staging environment on Heroku
  - provider: heroku
    api_key:
      secure: gGZwXnv/+n5J1qRzcbm8hQZxg9eToNPKNm0Vjs2S05kVzq67sPZD0MlfzUyx1ejqZTS7FWxkTWspAs3QTgJC7HsTXGY0qIenK/m9KkUKMpEgd35hMBLJx516kQgO1GAFkJSYp/AvIVN6krqs0Z96U0eshKdmWdINO6PTa95QLds=
    app: rainforest-ci-sample-staging
    on:
      repo: rainforestapp/ci-sample
      branch: develop
    # Run a script after the deploy. This starts Rainforest and pushes to master
    run: "env ./bin/rainforest_cd"

  # Deploy to our production environment on Heroku
  - provider: heroku
    api_key:
      secure: gGZwXnv/+n5J1qRzcbm8hQZxg9eToNPKNm0Vjs2S05kVzq67sPZD0MlfzUyx1ejqZTS7FWxkTWspAs3QTgJC7HsTXGY0qIenK/m9KkUKMpEgd35hMBLJx516kQgO1GAFkJSYp/AvIVN6krqs0Z96U0eshKdmWdINO6PTa95QLds=
    app: rainforest-ci-sample-prd
    on:
      repo: rainforestapp/ci-sample
      branch: master

