language: ruby
rvm:
- 2.7.1

jobs:
  include:
    - stage: install
    - stage: run_unit_tests
      script:
      # Run unit tests
      - bundle exec rake
    - stage: run_rainforest_tests
      script:
      # Install the latest stable version of rainforest-cli.
      # This will allow us to trigger a Rainforest run after each deploy.
      - wget "https://bin.equinox.io/c/htRtQZagtfg/rainforest-cli-stable-linux-amd64.tgz"
      - tar xvf rainforest-cli-stable-linux-amd64.tgz
      - sudo mv rainforest /usr/local/bin/
      # Trigger Rainforest run and wait for results
      - /usr/local/bin/rainforest run all --browsers chrome --token $RAINFOREST_TOKEN
    - stage: deploy_staging
      script:
      # Deploy to our staging environment on Heroku
      - provider: heroku
        api_key:
          secure: CJdkaqDYW9GB4Sh73nhnQYeJ11O7ebSd+BtMwVA9LcU+y4bZ7VmAPk/heXmNwabe0yJ8QoHhULE8JEm0t2pzKYB+VAi2yt4gsKQ4RMW1KsJGo3xLrnv1IZs67BIXxdeq3WNq+kIcO106ZeHfKaKpUpV9DdcO+IfBAQOpz8jc1eU=
        app: rainforest-ci-sample-staging
        on:
          repo: rainforestapp/ci-sample
          branch: develop
    - stage: deploy_prod
      script:
      # Deploy to our master environment on Heroku
      - provider: heroku
        api_key:
          secure: CJdkaqDYW9GB4Sh73nhnQYeJ11O7ebSd+BtMwVA9LcU+y4bZ7VmAPk/heXmNwabe0yJ8QoHhULE8JEm0t2pzKYB+VAi2yt4gsKQ4RMW1KsJGo3xLrnv1IZs67BIXxdeq3WNq+kIcO106ZeHfKaKpUpV9DdcO+IfBAQOpz8jc1eU=
        app: rainforest-ci-sample-prd
        on:
          repo: rainforestapp/ci-sample
          branch: master

# Configure the RAINFOREST_TOKEN environment variable. You can get the secure
# string by running 'travis encrypt RAINFOREST_TOKEN=<my_token>'
env:
  global:
    secure: "ZFOc6JbZ5jeI0Gyg+oPWtzhIN7pJkiBKg4q5vy0hdogM1ySB5nWNIj1J283Ne5mvn2eg55lJEn49Gk9tO6EOhLWGp1v4DP6QiWNFIDkW0w0kaDdpq4mx5CEFSlUszo5zawdkMzixaMBY1EpA/Jgbi7BwRdbNqdkr2PLpcF9uVRY="

install:
  - bundle install
